name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Uncomment if using Prisma:
      # - name: Generate Prisma client
      #   run: cd backend && npx prisma generate

      # Uncomment if using Orval:
      # - name: Generate Orval API client
      #   run: cd frontend && npx orval

      - name: Run code quality checks
        run: npm run cq
